# Generated by Django 3.0.3 on 2020-03-04 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100)),
                ('terme1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terme1', to='chatbot.Terme')),
                ('terme2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terme2', to='chatbot.Terme')),
            ],
        ),
    ]
