# Generated by Django 3.0.3 on 2020-03-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='poid',
            field=models.IntegerField(default=70),
            preserve_default=False,
        ),
    ]
