# Generated by Django 3.0.3 on 2020-03-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_relation_poid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terme',
            name='id',
        ),
        migrations.AlterField(
            model_name='terme',
            name='terme',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('terme1', 'relation', 'terme2')},
        ),
    ]
