# Generated by Django 3.0.3 on 2020-03-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20200304_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='poid',
            new_name='poids',
        ),
    ]
