# Generated by Django 3.0.4 on 2020-03-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20200308_1638'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='RelationAVerifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100)),
                ('poids', models.IntegerField()),
                ('terme1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ter1', to='chatbot.Terme')),
                ('terme2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ter2', to='chatbot.Terme')),
            ],
        ),
    ]
